"""Enforce the repository layout conventions. CI-friendly.

Two severities:
  - ERROR  : structural violation; exits 1.
  - WARN   : informational (e.g. paper/main.tex not shipped, or src/ modules with
             __main__ blocks pending migration to scripts/<verb>/). Does not fail.

Checks:
  1.  [ERROR] scripts/<verb>/ uses ONLY the closed verb set.
  2.  [ERROR] scripts/ root contains no loose files.
  3.  [WARN]  src/ modules with `if __name__ == "__main__"` blocks.
  4.  [ERROR] No stray .py at experiments/ root (loose scripts wrapped in <id>/scripts/).
  5.  [ERROR] Top-level dirs match the expected set; underscore-prefix dirs always allowed.
  6.  [ERROR] Every experiments/<id>/ has a README.md.
  7.  [ERROR] experiments/<id>/ ↔ experiments.yaml entry parity (no orphans either side).
  8.  [WARN]  Every \\label{fig:...} in paper/main.tex appears in some experiment's
              paper_labels: in experiments.yaml. Warning (not error) because some labels
              are inline-defined (tables) or commented out. If paper/main.tex is not
              shipped this is WARNed (skipped), never silently passed.
  9.  [ERROR] A top-level README.md exists (the repo front door is mandatory).
  10. [ERROR] No file under scripts/ imports `experiments` or `scripts` packages; the
              presentation/entry layer depends ONLY on src/, never on experiment-private
              or sibling-script modules.
  11. [WARN]  experiments.yaml internal consistency (no tex needed): every label under an
              experiment's paper_figures: also appears in its paper_labels:, and every
              source path referenced by entry:/scripts_dir/figures_dir exists on disk
              (regenerable gitignored output trees — figures/, results/ — are exempt).
  12. [ERROR] Path-resolution guard: every *committed input* an experiment declares in
              experiments.yaml (entry-script paths, scripts_dir, and committed DATA
              files/dirs named in paper_figures:) actually resolves on disk. Only paths
              that are genuinely committed inputs — under data/derived/**, scripts/**, or
              experiments/** — are asserted. Regenerable gitignored output trees
              (figures/, results/, paper/, reports/), the external SSD root
              (${UM_SSD_ROOT}/local_snapshots/$VAR), globbed/placeholder paths, and
              gitignored output artefacts — bulk tensors/plots AND the regenerated
              derived-metric sidecars (.csv/.json), since this is a code-only release
              that ships no metrics — are exempt.
              When it is ambiguous whether a reference is a committed input or a
              regenerable output, the case is downgraded to WARN (see
              check_manifest_consistency) rather than ERRORed.

Run:
    uv run python scripts/audit/check_layout.py            # warnings + errors
    uv run python scripts/audit/check_layout.py --strict   # warnings count as errors
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
EXPERIMENTS_YAML = REPO / "experiments.yaml"
PAPER_TEX = REPO / "paper" / "main.tex"
README = REPO / "README.md"

# Top-level dirs holding regenerable, gitignored outputs: paths under these are not
# expected to exist in a clean checkout, so manifest path-existence checks skip them.
REGENERABLE_OUTPUT_ROOTS = {"figures", "results"}

# Roots exempt from the committed-input path-RESOLUTION guard (check 12): regenerable
# gitignored output trees plus the paper/reports trees pruned from the public repo
# (.gitignore: /paper/, /reports/). References under these are not committed inputs, so
# their absence in a clean checkout is expected, not a "dangling reference".
RESOLUTION_EXEMPT_ROOTS = REGENERABLE_OUTPUT_ROOTS | {"paper", "reports"}

# Top-level dirs that DO hold committed inputs we can assert the existence of.
COMMITTED_INPUT_ROOTS = {"data", "scripts", "experiments"}

# Suffixes of gitignored output artefacts that live under committed-input trees but
# are regenerated, not shipped (.gitignore: experiments/**/*.pt etc., **/derived/**/*).
# This is a CODE-ONLY release: no data and no derived metrics ship, so the per-figure
# metric sidecars (.csv/.json) and bulk tensors/plots are all regenerated by running
# the experiment scripts. A reference to one of these is a regenerable output, not a
# missing committed input.
GITIGNORED_ARTEFACT_SUFFIXES = {
    ".pt",
    ".pth",
    ".npy",
    ".npz",
    ".pdf",
    ".png",
    ".csv",
    ".json",
}

ALLOWED_SCRIPT_VERBS = {"train", "extract", "eval", "audit"}
ALLOWED_TOP_LEVEL = {
    "src",
    "scripts",
    "experiments",
    "examples",  # CPU-only runnable library-reuse demos
    "notebooks",  # Colab-ready guided tours of the paper's core analyses
    "data",  # committed small derived inputs (data/derived/**) that drive figures
    "figures",
    "results",
    "logs",  # runtime job logs (gitignored; created by Makefile / launch scripts)
    "local_snapshots",  # default UM_SSD_ROOT output root (gitignored; created by any default run)
    "reports",
    "docs",  # companion guides: REPRODUCE.md / DATA.md / THIRD_PARTY.md
    "paper",
    "configs",
    "tests",
    "lib",
    # underscore-prefix dirs (e.g. _archive/) are always allowed by check 5
}
# Files allowed at top level (REPRODUCE.md / DATA.md / THIRD_PARTY.md now live under docs/)
ALLOWED_TOP_FILES = {
    "README.md",
    "CITATION.cff",
    "LICENSE",
    "Makefile",
    "pyproject.toml",
    "uv.lock",
    "experiments.yaml",
    ".gitignore",
    ".rgignore",
    ".env.example",
}


def _is_hidden(p: Path) -> bool:
    return p.name.startswith(".")


def check_scripts_verbs() -> list[str]:
    issues: list[str] = []
    scripts = REPO / "scripts"
    if not scripts.exists():
        return issues
    for p in scripts.iterdir():
        if _is_hidden(p):
            continue
        if p.is_file():
            issues.append(f"loose file in scripts/ root: {p.name} (must be in scripts/<verb>/)")
        elif p.is_dir():
            name = p.name.lstrip("_")
            if p.name.startswith("_"):
                continue  # _legacy etc.
            if name not in ALLOWED_SCRIPT_VERBS:
                issues.append(f"unknown verb scripts/{p.name}/ (allowed: {sorted(ALLOWED_SCRIPT_VERBS)})")
    return issues


def check_src_no_main() -> list[str]:
    issues: list[str] = []
    src = REPO / "src"
    if not src.exists():
        return issues
    for p in src.rglob("*.py"):
        if "__pycache__" in p.parts:
            continue
        try:
            text = p.read_text()
        except (UnicodeDecodeError, OSError):
            continue
        if 'if __name__ == "__main__"' in text or "if __name__ == '__main__'" in text:
            issues.append(f"src/ module has __main__ block: {p.relative_to(REPO)}")
    return issues


def check_experiments_no_loose() -> list[str]:
    """No loose .py at experiments/ root or inside topic dirs.

    Layout is 2-level: `experiments/<topic>/<id>/` (with README.md at the leaf).
    Topic dirs (depth 1, no README) must contain only sub-dirs.
    """
    issues: list[str] = []
    exp = REPO / "experiments"
    if not exp.exists():
        return issues
    for p in exp.iterdir():
        if _is_hidden(p):
            continue
        if p.suffix == ".py" and p.name != "__init__.py":
            issues.append(f"loose .py at experiments/ root: {p.name} (wrap in experiments/<topic>/<id>/scripts/)")
    for top in exp.iterdir():
        if not top.is_dir() or _is_hidden(top) or top.name.startswith("_") or top.name == "__pycache__":
            continue
        if (top / "README.md").exists():
            issues.append(f"unexpected depth-1 experiment dir: experiments/{top.name}/ (use experiments/<topic>/<id>/)")
            continue
        for sub in top.iterdir():
            if _is_hidden(sub) or sub.name == "__pycache__":
                continue
            if sub.suffix == ".py" and sub.name != "__init__.py":
                issues.append(
                    f"loose .py in topic dir experiments/{top.name}/: {sub.name} (move into experiments/{top.name}/<id>/)"
                )
    return issues


def check_top_level() -> list[str]:
    issues: list[str] = []
    for p in REPO.iterdir():
        if _is_hidden(p):
            continue
        # underscore-prefix marks internal/legacy dirs (e.g. _legacy/); always allowed
        if p.name.startswith("_"):
            continue
        if p.is_dir() and p.name not in ALLOWED_TOP_LEVEL:
            issues.append(f"unexpected top-level dir: {p.name}")
        elif p.is_file() and p.name not in ALLOWED_TOP_FILES:
            issues.append(f"unexpected top-level file: {p.name}")
    return issues


def check_readme_exists() -> list[str]:
    """The repo front door is mandatory."""
    if not README.exists():
        return ["top-level README.md missing (the repo front door is mandatory)"]
    return []


# from experiments[.…] / import experiments[.…]
_FORBIDDEN_SCRIPT_IMPORT = re.compile(r"^\s*(?:from|import)\s+(experiments)(?:\.|\s|,|$)")


def check_scripts_imports() -> list[str]:
    """scripts/ is the presentation/entry layer: it must not depend on experiments/.

    Importing `experiments.*` reaches into experiment-private code (a layering
    inversion). Intra-`scripts/` imports of a shared helper module are allowed:
    that is deduplication within the layer, not a cross-layer dependency.
    """
    issues: list[str] = []
    scripts = REPO / "scripts"
    if not scripts.exists():
        return issues
    for p in sorted(scripts.rglob("*.py")):
        if "__pycache__" in p.parts:
            continue
        try:
            text = p.read_text()
        except (UnicodeDecodeError, OSError):
            continue
        for lineno, line in enumerate(text.splitlines(), start=1):
            m = _FORBIDDEN_SCRIPT_IMPORT.match(line)
            if m:
                issues.append(
                    f"{p.relative_to(REPO)}:{lineno} imports {m.group(1)!r} "
                    f"(scripts/ must depend only on src/): {line.strip()}"
                )
    return issues


def _experiment_dirs() -> list[Path]:
    """Leaf experiment dirs across the 2-level topic layout.

    A leaf is a directory containing README.md at depth 2
    (`experiments/<topic>/<id>/`).
    """
    exp = REPO / "experiments"
    if not exp.exists():
        return []
    leaves: list[Path] = []
    for top in sorted(exp.iterdir()):
        if not top.is_dir() or top.name.startswith("_") or _is_hidden(top) or top.name == "__pycache__":
            continue
        if (top / "README.md").exists():
            leaves.append(top)
            continue
        for child in sorted(top.iterdir()):
            if not child.is_dir() or child.name.startswith("_") or _is_hidden(child) or child.name == "__pycache__":
                continue
            if (child / "README.md").exists():
                leaves.append(child)
    return leaves


def _load_experiments_yaml() -> dict | None:
    if not EXPERIMENTS_YAML.exists():
        return None
    try:
        import yaml  # type: ignore
    except ImportError:
        return None
    return yaml.safe_load(EXPERIMENTS_YAML.read_text())


def check_experiment_readmes() -> list[str]:
    return [f"experiments/{p.name}/ missing README.md" for p in _experiment_dirs() if not (p / "README.md").exists()]


def check_yaml_dir_parity() -> list[str]:
    issues: list[str] = []
    data = _load_experiments_yaml()
    if data is None:
        return ["experiments.yaml not found or pyyaml not installed"]
    yaml_ids = {e["id"] for e in (data.get("experiments") or []) if "id" in e}
    dir_ids = {p.name for p in _experiment_dirs()}
    for orphan in sorted(dir_ids - yaml_ids):
        issues.append(
            f"experiments/{orphan}/ has no entry in experiments.yaml (add one or rename to underscore-prefix)"
        )
    for orphan in sorted(yaml_ids - dir_ids):
        issues.append(f"experiments.yaml entry id={orphan!r} has no matching experiments/{orphan}/ dir")
    return issues


def check_paper_label_coverage() -> list[str]:
    if not PAPER_TEX.exists():
        return ["paper/main.tex not shipped — figure-label coverage check skipped"]
    data = _load_experiments_yaml()
    if data is None:
        return []
    paper_text = PAPER_TEX.read_text()
    # Strip LaTeX line comments before regex (a leading % comments out the rest of the line)
    stripped = re.sub(r"(?<!\\)%.*", "", paper_text)
    labels_in_paper = set(re.findall(r"\\label\{(fig:[a-zA-Z0-9_-]+)\}", stripped))
    labels_in_yaml = {label for e in (data.get("experiments") or []) for label in (e.get("paper_labels") or [])}
    labels_in_yaml.update(data.get("paper_only_labels") or [])
    return [
        f"paper label {label!r} has no producer in experiments.yaml (add to an experiment's paper_labels or top-level paper_only_labels)"
        for label in sorted(labels_in_paper - labels_in_yaml)
    ]


def _entry_script(cmd: str) -> str | None:
    """First token ending in .py in an `entry:` command (the script path)."""
    for tok in cmd.split():
        if tok.endswith(".py"):
            return tok
    return None


def _path_is_regenerable(rel: str) -> bool:
    """True if `rel`'s top-level dir is a gitignored, regenerable output tree."""
    head = rel.lstrip("./").split("/", 1)[0]
    return head in REGENERABLE_OUTPUT_ROOTS


def check_manifest_consistency() -> list[str]:
    """experiments.yaml internal consistency, without needing paper/main.tex.

    Two families of WARN (not ERROR — labels may be legitimately shared across
    experiments and paths may point at not-yet-materialised outputs):
      - every label under an experiment's paper_figures: also appears in its
        paper_labels: list;
      - every source path referenced by entry:/scripts_dir/figures_dir exists on
        disk. Regenerable gitignored output trees (figures/, results/) are exempt,
        as are glob patterns and ${VAR}/off-repo paths.
    """
    data = _load_experiments_yaml()
    if data is None:
        return []
    issues: list[str] = []
    for e in data.get("experiments") or []:
        eid = e.get("id", "<no-id>")
        labels = set(e.get("paper_labels") or [])
        for pf in e.get("paper_figures") or []:
            if "->" not in pf:
                continue
            label = pf.split("->")[-1].strip()
            if label and label not in labels:
                issues.append(f"experiment {eid!r}: paper_figures label {label!r} is not in its paper_labels: list")
        refs: list[str] = []
        for key in ("scripts_dir", "figures_dir"):
            val = e.get(key)
            if isinstance(val, str) and val.strip():
                refs.append(val.strip())
        for cmd in e.get("entry") or []:
            script = _entry_script(cmd)
            if script:
                refs.append(script)
        for ref in refs:
            # Skip globs, env-var/off-repo paths, and regenerable output trees.
            if any(c in ref for c in "*?[") or ref.startswith("$") or "${" in ref:
                continue
            if _path_is_regenerable(ref):
                continue
            if not (REPO / ref).exists():
                issues.append(f"experiment {eid!r}: referenced path {ref!r} does not exist on disk")
    return issues


def _paper_figure_source(pf: str) -> str | None:
    """Source path on the LHS of a `<source> -> <label>` paper_figures: entry."""
    if "->" not in pf:
        return None
    src = pf.split("->", 1)[0].strip()
    return src or None


def _is_external_or_pattern(ref: str) -> bool:
    """True for refs we can never resolve on disk: env-var/off-repo paths, globs, and
    `...` ellipsis placeholders (e.g. `.../run0/.../shards/x.json` documenting a
    run-id-dependent output path, not a literal committed file)."""
    if ref.startswith("$") or "${" in ref or "local_snapshots" in ref:
        return True
    if any(c in ref for c in "*?[<>"):
        return True
    if "..." in ref or "/." in ref:  # `.../`-style placeholder segment
        return True
    return False


def _classify_committed_ref(ref: str) -> str:
    """Triage a manifest path reference for the resolution guard (check 12).

    Returns one of:
      "committed" — a genuinely committed input whose absence is an ERROR;
      "ambiguous" — a repo-relative path that is neither clearly committed nor clearly
                    regenerable (absence WARNed, never ERRORed — stay conservative);
      "exempt"    — external/glob/placeholder path or a regenerable/gitignored output
                    tree or artefact; not asserted at all.
    """
    if _is_external_or_pattern(ref):
        return "exempt"
    head = ref.lstrip("./").split("/", 1)[0]
    if head in RESOLUTION_EXEMPT_ROOTS:
        return "exempt"
    # Gitignored binary artefacts under committed-input trees are regenerated outputs.
    if Path(ref).suffix in GITIGNORED_ARTEFACT_SUFFIXES:
        return "exempt"
    if head in COMMITTED_INPUT_ROOTS:
        return "committed"
    return "ambiguous"


def check_committed_paths_resolve() -> tuple[list[str], list[str]]:
    """Path-RESOLUTION guard: committed inputs declared in experiments.yaml must exist.

    The original layout audit found 3 'not reproducible' cases caused by references to
    files that do not exist on disk. This turns that class of dangling-reference into a
    CI failure — but ONLY for genuinely committed inputs (entry-script paths, scripts_dir,
    and committed DATA files/dirs named in paper_figures:). Regenerable/gitignored output
    trees (figures/, results/, paper/, reports/), the external SSD root, globbed or
    `...`-placeholder paths, and gitignored binary artefacts are exempt. Ambiguous
    repo-relative refs are WARNed rather than ERRORed, so the guard stays conservative
    (zero false ERRORs on the current clean tree).

    Returns (errors, warnings).
    """
    data = _load_experiments_yaml()
    if data is None:
        return [], []
    errors: list[str] = []
    warnings: list[str] = []
    for e in data.get("experiments") or []:
        eid = e.get("id", "<no-id>")
        # (source-kind, ref) so error messages name where the dangling ref came from.
        refs: list[tuple[str, str]] = []
        sd = e.get("scripts_dir")
        if isinstance(sd, str) and sd.strip():
            refs.append(("scripts_dir", sd.strip()))
        for cmd in e.get("entry") or []:
            script = _entry_script(cmd)
            if script:
                refs.append(("entry script", script))
        for pf in e.get("paper_figures") or []:
            src = _paper_figure_source(pf)
            if src:
                refs.append(("paper_figures source", src))
        seen: set[str] = set()
        for kind, ref in refs:
            if ref in seen:
                continue
            seen.add(ref)
            verdict = _classify_committed_ref(ref)
            if verdict == "exempt":
                continue
            if (REPO / ref).exists():
                continue
            msg = f"experiment {eid!r}: committed {kind} {ref!r} does not resolve on disk"
            if verdict == "committed":
                errors.append(msg)
            else:  # ambiguous — stay conservative
                warnings.append(
                    f"experiment {eid!r}: {kind} {ref!r} does not resolve on disk "
                    f"(ambiguous committed-vs-regenerable; not failing CI)"
                )
    return errors, warnings


def main() -> int:
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument("--strict", action="store_true", help="warnings count as errors")
    args = parser.parse_args()

    errors: list[str] = []
    warnings: list[str] = []
    errors += check_scripts_verbs()
    errors += check_experiments_no_loose()
    errors += check_top_level()
    errors += check_experiment_readmes()
    errors += check_yaml_dir_parity()
    errors += check_readme_exists()
    errors += check_scripts_imports()
    resolve_errors, resolve_warnings = check_committed_paths_resolve()
    errors += resolve_errors
    warnings += check_src_no_main()
    warnings += check_paper_label_coverage()
    warnings += check_manifest_consistency()
    warnings += resolve_warnings

    if warnings:
        print(f"{len(warnings)} informational warning(s):", file=sys.stderr)
        for w in warnings:
            print(f"  W {w}", file=sys.stderr)
    if errors:
        print(f"{len(errors)} error(s):", file=sys.stderr)
        for e in errors:
            print(f"  E {e}", file=sys.stderr)
        return 1
    if args.strict and warnings:
        return 1
    print(f"layout OK ({len(warnings)} warnings)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
